# Generated by Django 4.0 on 2022-03-20 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0002_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(max_length=2)),
                ('occupied_status', models.CharField(choices=[('Yes', 'Occupied'), ('No', 'Not Occupied')], default='No', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_lot', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='bike', to='bike.lot')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bike', to='bike.user')),
            ],
        ),
    ]
