# Generated by Django 4.0 on 2022-03-21 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0003_lot_bike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='current_lot',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='bike', to='bike.lot'),
        ),
        migrations.AlterField(
            model_name='bike',
            name='owner',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='bike', to='bike.user'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='occupied_status',
            field=models.CharField(choices=[('Yes', 'Occupied'), ('No', 'Not Occupied')], default=None, max_length=3),
        ),
    ]
